version: 0.1
env:
  - name: STORAGE_ACCOUNT_NAME
    value: "mitestsa"
  - name: STORAGE_CONTAINER_NAME
    value: "mitestsa-container"
  - name: MI_CLIENT_ID
    value: "b24d4637-3453-4f6f-8187-228a5442a675"
enableFeatures:
  - ManagedIdentity